name: Master

on:
  push:
    branches:
      - master
      
jobs:
  cra-template-publish:
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 12
           registry-url: https://registry.npmjs.org/
           
           
       - name: Git Config
         run: |
           git config --local user.email "${{secrets.GIT_EMAIL}}" 
           git config --local user.name "${{secrets.GIT_USERNAME}}"
         
       - name: npm version patch
         run: npm version patch
         
         
       - name: Version PR
         uses: repo-sync/pull-request@v2.6
         with:
            destination_branch: "release"
            github_token: ${{secrets.GIT_TOKEN}}
             
       - name: npm publish
         if: ${{job.status}} == success
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
         run: npm publish 

       

