name: Master

on:
  push:
    branches:
      - master
      
jobs:
  cra-template-publish:
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 12
           registry-url: https://registry.npmjs.org/
           
       - name: set git profile
         run: |
           git conifg --local user.email "${{secrets.GIT_EMAIL}}" 
           git config --local user.name "${{secrets.GIT_USERNAME}}"
         
       - name: npm version patch
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
         run: npm version patch && PACKAGE_VERSION=$(grep '"version":' package.json -m1 | cut -d\" -f4) && echo version_$PACKAGE_VERSION

       - name: npm publish
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
         run: npm publish 
       

