name: Master

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Semantic Version Bump Type (major minor patch)'
        required: true
  push:
    branches:
      - master
      
jobs:
  cra-template-publish:
    runs-on: ubuntu-latest
    steps: 
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: 12
           registry-url: https://registry.npmjs.org/
           
       - name: update
         uses: bcomnes/npm-bump@v1.0.4
         with:
           git_email: ${{secrets.GIT_EMAIL}}
           git_username: ${{secrets.GIT_USERNAME}}
           newversion: ${{ github.event.inputs.newversion }}
           push_version_commit: true
           github_token: ${{secrets.GIT_TOKEN}}
           npm_token: ${{secrets.NPM_PUBLISH_TOKEN}}
           
#        - name: Git Config
#          run: |
#            git config --local user.email "${{secrets.GIT_EMAIL}}" 
#            git config --local user.name "${{secrets.GIT_USERNAME}}"
         
#        - name: npm version patch
#          env:

#          run: npm version patch && PACKAGE_VERSION=$(grep '"version":' package.json -m1 | cut -d\" -f4) 
         
         
#        - name: GitHub release push
#          uses: ad-m/github-push-action@v0.6.0
#          with:
#             github_token: ${{secrets.GIT_TOKEN}}
#             branch: release
             
#        - name: npm publish
#          if: ${{job.status}} == success
#          env:
#            NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
#          run: npm publish 

       

